apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange
  labels:
    app: currency-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
      - name: app
        image: ghcr.io/alexrocco/my-dashboard/currency-exchange:20220501082815 # {"$imagepolicy": "flux-system:currency-exchange"}
        ports:
        - containerPort: 8080
        env:
        - name: FROM
          value: EUR
        - name: TO
          value: BRL
