apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: currency-exchange
  namespace: flux-system
spec:
  image: ghcr.io/alexrocco/my-dashboard/currency-exchange
  interval: 1m0s
