
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: currency-exchange
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./exporters/currency-exchange/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default